application: future-glider-87801
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: minimal/static

- url: .*
  script: minimal.app


libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"

skip_files:
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$
- ^(.*/)?.*\.log$
- ^env$
- ^csv$
- ^spiders$
- ^Session.vim$
