select  `scoring_team`,
        `scoring_playoffs_team`,
        `returns_team`,
        `returns_playoffs_team`,
        `receiving_and_rushing_team`,
        `receiving_and_rushing_playoffs_team`,
        `passing_team`,
        `passing_playoffs_team`,
        `passing_advanced_team`,
        `kicking_team`,
        `defense_team`,
        `defense_playoffs_team`
from player_seasons        
limit 10;







select count(*),
IFNULL(`scoring_team` IS NOT NULL, 0) +
IFNULL(`scoring_playoffs_team` IS NOT NULL, 0) +
IFNULL(`returns_team` IS NOT NULL, 0) +
IFNULL(`returns_playoffs_team` IS NOT NULL, 0) +
IFNULL(`receiving_and_rushing_team` IS NOT NULL, 0) +
IFNULL(`receiving_and_rushing_playoffs_team` IS NOT NULL, 0) +
IFNULL(`passing_team` IS NOT NULL, 0) +
IFNULL(`passing_playoffs_team` IS NOT NULL, 0) +
IFNULL(`passing_advanced_team` IS NOT NULL, 0) +
IFNULL(`kicking_team` IS NOT NULL, 0) +
IFNULL(`defense_team` IS NOT NULL, 0) +
IFNULL(`defense_playoffs_team` IS NOT NULL, 0) num_fields
from player_seasons
group by num_fields;


 CREATE TABLE `player_seasons` (
    `defense_age` int(11) DEFAULT NULL,
    `defense_av` int(11) DEFAULT NULL,
    `defense_def_int` int(11) DEFAULT NULL,
    `defense_def_int_long` int(11) DEFAULT NULL,
    `defense_def_int_td` int(11) DEFAULT NULL,
    `defense_def_int_yds` int(11) DEFAULT NULL,
    `defense_fumbles` int(11) DEFAULT NULL,
    `defense_fumbles_forced` int(11) DEFAULT NULL,
    `defense_fumbles_rec` int(11) DEFAULT NULL,
    `defense_fumbles_rec_td` int(11) DEFAULT NULL,
    `defense_fumbles_rec_yds` int(11) DEFAULT NULL,
    `defense_g` int(11) DEFAULT NULL,
    `defense_gs` int(11) DEFAULT NULL,
    `defense_pass_defended` int(11) DEFAULT NULL,
    `defense_playoffs_age` int(11) DEFAULT NULL,
    `defense_playoffs_def_int` int(11) DEFAULT NULL,
    `defense_playoffs_def_int_long` int(11) DEFAULT NULL,
    `defense_playoffs_def_int_td` int(11) DEFAULT NULL,
    `defense_playoffs_def_int_yds` int(11) DEFAULT NULL,
    `defense_playoffs_fumbles` int(11) DEFAULT NULL,
    `defense_playoffs_fumbles_forced` int(11) DEFAULT NULL,
    `defense_playoffs_fumbles_rec` int(11) DEFAULT NULL,
    `defense_playoffs_fumbles_rec_td` int(11) DEFAULT NULL,
    `defense_playoffs_fumbles_rec_yds` int(11) DEFAULT NULL,
    `defense_playoffs_g` int(11) DEFAULT NULL,
    `defense_playoffs_gs` int(11) DEFAULT NULL,
    `defense_playoffs_pass_defended` int(11) DEFAULT NULL,
    `defense_playoffs_pos` varchar(13) DEFAULT NULL,
    `defense_playoffs_sacks` float DEFAULT NULL,
    `defense_playoffs_safety_md` int(11) DEFAULT NULL,
    `defense_playoffs_tackles_assists` int(11) DEFAULT NULL,
    `defense_playoffs_tackles_solo` int(11) DEFAULT NULL,
    `defense_playoffs_team` varchar(3) DEFAULT NULL,
    `defense_playoffs_year_id` int(11) DEFAULT NULL,
    `defense_pos` varchar(21) DEFAULT NULL,
    `defense_sacks` float DEFAULT NULL,
    `defense_safety_md` int(11) DEFAULT NULL,
    `defense_tackles_assists` int(11) DEFAULT NULL,
    `defense_tackles_solo` int(11) DEFAULT NULL,
    `defense_team` varchar(3) DEFAULT NULL,
    `defense_uniform_number` int(11) DEFAULT NULL,
    `defense_year_id` varchar(6) DEFAULT NULL,
    `kicking_age` int(11) DEFAULT NULL,
    `kicking_av` int(11) DEFAULT NULL,
    `kicking_fg_perc` varchar(6) DEFAULT NULL,
    `kicking_fga` int(11) DEFAULT NULL,
    `kicking_fga1` int(11) DEFAULT NULL,
    `kicking_fga2` int(11) DEFAULT NULL,
    `kicking_fga3` int(11) DEFAULT NULL,
    `kicking_fga4` int(11) DEFAULT NULL,
    `kicking_fga5` int(11) DEFAULT NULL,
    `kicking_fgm` int(11) DEFAULT NULL,
    `kicking_fgm1` int(11) DEFAULT NULL,
    `kicking_fgm2` int(11) DEFAULT NULL,
    `kicking_fgm3` int(11) DEFAULT NULL,
    `kicking_fgm4` int(11) DEFAULT NULL,
    `kicking_fgm5` int(11) DEFAULT NULL,
    `kicking_g` int(11) DEFAULT NULL,
    `kicking_gs` int(11) DEFAULT NULL,
    `kicking_pos` varchar(13) DEFAULT NULL,
    `kicking_punt` int(11) DEFAULT NULL,
    `kicking_punt_blocked` int(11) DEFAULT NULL,
    `kicking_punt_long` int(11) DEFAULT NULL,
    `kicking_punt_yds` int(11) DEFAULT NULL,
    `kicking_punt_yds_per_punt` float DEFAULT NULL,
    `kicking_team` varchar(3) DEFAULT NULL,
    `kicking_uniform_number` int(11) DEFAULT NULL,
    `kicking_xp_perc` varchar(6) DEFAULT NULL,
    `kicking_xpa` int(11) DEFAULT NULL,
    `kicking_xpm` int(11) DEFAULT NULL,
    `kicking_year_id` varchar(5) DEFAULT NULL,
    `passing_advanced_age` int(11) DEFAULT NULL,
    `passing_advanced_g` int(11) DEFAULT NULL,
    `passing_advanced_gs` int(11) DEFAULT NULL,
    `passing_advanced_pass_adj_net_yds_per_att_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_adj_yds_per_att_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_att` int(11) DEFAULT NULL,
    `passing_advanced_pass_cmp_perc_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_int_perc_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_net_yds_per_att_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_rating_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_sacked_perc_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_td_perc_index` int(11) DEFAULT NULL,
    `passing_advanced_pass_yds_per_att_index` int(11) DEFAULT NULL,
    `passing_advanced_pos` varchar(12) DEFAULT NULL,
    `passing_advanced_qb_rec` varchar(6) DEFAULT NULL,
    `passing_advanced_team` varchar(3) DEFAULT NULL,
    `passing_advanced_uniform_number` int(11) DEFAULT NULL,
    `passing_advanced_year_id` varchar(5) DEFAULT NULL,
    `passing_age` int(11) DEFAULT NULL,
    `passing_av` int(11) DEFAULT NULL,
    `passing_comebacks` int(11) DEFAULT NULL,
    `passing_g` int(11) DEFAULT NULL,
    `passing_gs` int(11) DEFAULT NULL,
    `passing_gwd` int(11) DEFAULT NULL,
    `passing_pass_adj_net_yds_per_att` float DEFAULT NULL,
    `passing_pass_adj_yds_per_att` float DEFAULT NULL,
    `passing_pass_att` int(11) DEFAULT NULL,
    `passing_pass_cmp` int(11) DEFAULT NULL,
    `passing_pass_cmp_perc` float DEFAULT NULL,
    `passing_pass_int` int(11) DEFAULT NULL,
    `passing_pass_int_perc` float DEFAULT NULL,
    `passing_pass_long` int(11) DEFAULT NULL,
    `passing_pass_net_yds_per_att` float DEFAULT NULL,
    `passing_pass_rating` float DEFAULT NULL,
    `passing_pass_sacked` int(11) DEFAULT NULL,
    `passing_pass_sacked_perc` float DEFAULT NULL,
    `passing_pass_sacked_yds` int(11) DEFAULT NULL,
    `passing_pass_td` int(11) DEFAULT NULL,
    `passing_pass_td_perc` float DEFAULT NULL,
    `passing_pass_yds` int(11) DEFAULT NULL,
    `passing_pass_yds_per_att` float DEFAULT NULL,
    `passing_pass_yds_per_cmp` float DEFAULT NULL,
    `passing_pass_yds_per_g` float DEFAULT NULL,
    `passing_playoffs_age` int(11) DEFAULT NULL,
    `passing_playoffs_comebacks` int(11) DEFAULT NULL,
    `passing_playoffs_g` int(11) DEFAULT NULL,
    `passing_playoffs_gs` int(11) DEFAULT NULL,
    `passing_playoffs_gwd` int(11) DEFAULT NULL,
    `passing_playoffs_pass_adj_net_yds_per_att` float DEFAULT NULL,
    `passing_playoffs_pass_adj_yds_per_att` float DEFAULT NULL,
    `passing_playoffs_pass_att` int(11) DEFAULT NULL,
    `passing_playoffs_pass_cmp` int(11) DEFAULT NULL,
    `passing_playoffs_pass_cmp_perc` float DEFAULT NULL,
    `passing_playoffs_pass_int` int(11) DEFAULT NULL,
    `passing_playoffs_pass_int_perc` float DEFAULT NULL,
    `passing_playoffs_pass_long` int(11) DEFAULT NULL,
    `passing_playoffs_pass_net_yds_per_att` float DEFAULT NULL,
    `passing_playoffs_pass_rating` float DEFAULT NULL,
    `passing_playoffs_pass_sacked` int(11) DEFAULT NULL,
    `passing_playoffs_pass_sacked_perc` float DEFAULT NULL,
    `passing_playoffs_pass_sacked_yds` int(11) DEFAULT NULL,
    `passing_playoffs_pass_td` int(11) DEFAULT NULL,
    `passing_playoffs_pass_td_perc` float DEFAULT NULL,
    `passing_playoffs_pass_yds` int(11) DEFAULT NULL,
    `passing_playoffs_pass_yds_per_att` float DEFAULT NULL,
    `passing_playoffs_pass_yds_per_cmp` float DEFAULT NULL,
    `passing_playoffs_pass_yds_per_g` float DEFAULT NULL,
    `passing_playoffs_pos` varchar(7) DEFAULT NULL,
    `passing_playoffs_qb_rec` varchar(3) DEFAULT NULL,
    `passing_playoffs_team` varchar(3) DEFAULT NULL,
    `passing_playoffs_year_id` int(11) DEFAULT NULL,
    `passing_pos` varchar(12) DEFAULT NULL,
    `passing_qb_rec` varchar(6) DEFAULT NULL,
    `passing_qbr` float DEFAULT NULL,
    `passing_team` varchar(3) DEFAULT NULL,
    `passing_uniform_number` int(11) DEFAULT NULL,
    `passing_year_id` varchar(5) DEFAULT NULL,
    `player_id` int(11) DEFAULT NULL,
    `player_seasons_id` int(11) NOT NULL AUTO_INCREMENT,
    `receiving_and_rushing_age` int(11) DEFAULT NULL,
    `receiving_and_rushing_av` int(11) DEFAULT NULL,
    `receiving_and_rushing_fumbles` int(11) DEFAULT NULL,
    `receiving_and_rushing_g` int(11) DEFAULT NULL,
    `receiving_and_rushing_gs` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_age` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_fumbles` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_g` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_gs` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_pos` varchar(10) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec_long` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec_per_g` float DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec_td` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec_yds` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec_yds_per_g` float DEFAULT NULL,
    `receiving_and_rushing_playoffs_rec_yds_per_rec` float DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_att` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_att_per_g` float DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_long` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_receive_td` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_td` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_yds` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_yds_per_att` float DEFAULT NULL,
    `receiving_and_rushing_playoffs_rush_yds_per_g` float DEFAULT NULL,
    `receiving_and_rushing_playoffs_targets` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_team` varchar(3) DEFAULT NULL,
    `receiving_and_rushing_playoffs_yds_from_scrimmage` int(11) DEFAULT NULL,
    `receiving_and_rushing_playoffs_year_id` int(11) DEFAULT NULL,
    `receiving_and_rushing_pos` varchar(13) DEFAULT NULL,
    `receiving_and_rushing_rec` int(11) DEFAULT NULL,
    `receiving_and_rushing_rec_long` int(11) DEFAULT NULL,
    `receiving_and_rushing_rec_per_g` float DEFAULT NULL,
    `receiving_and_rushing_rec_td` int(11) DEFAULT NULL,
    `receiving_and_rushing_rec_yds` int(11) DEFAULT NULL,
    `receiving_and_rushing_rec_yds_per_g` float DEFAULT NULL,
    `receiving_and_rushing_rec_yds_per_rec` float DEFAULT NULL,
    `receiving_and_rushing_rush_att` int(11) DEFAULT NULL,
    `receiving_and_rushing_rush_att_per_g` float DEFAULT NULL,
    `receiving_and_rushing_rush_long` int(11) DEFAULT NULL,
    `receiving_and_rushing_rush_receive_td` int(11) DEFAULT NULL,
    `receiving_and_rushing_rush_td` int(11) DEFAULT NULL,
    `receiving_and_rushing_rush_yds` int(11) DEFAULT NULL,
    `receiving_and_rushing_rush_yds_per_att` float DEFAULT NULL,
    `receiving_and_rushing_rush_yds_per_g` float DEFAULT NULL,
    `receiving_and_rushing_targets` int(11) DEFAULT NULL,
    `receiving_and_rushing_team` varchar(3) DEFAULT NULL,
    `receiving_and_rushing_uniform_number` int(11) DEFAULT NULL,
    `receiving_and_rushing_yds_from_scrimmage` int(11) DEFAULT NULL,
    `receiving_and_rushing_year_id` varchar(5) DEFAULT NULL,
    `returns_age` int(11) DEFAULT NULL,
    `returns_all_purpose_yds` int(11) DEFAULT NULL,
    `returns_av` int(11) DEFAULT NULL,
    `returns_g` int(11) DEFAULT NULL,
    `returns_gs` int(11) DEFAULT NULL,
    `returns_kick_ret` int(11) DEFAULT NULL,
    `returns_kick_ret_long` int(11) DEFAULT NULL,
    `returns_kick_ret_td` int(11) DEFAULT NULL,
    `returns_kick_ret_yds` int(11) DEFAULT NULL,
    `returns_kick_ret_yds_per_ret` float DEFAULT NULL,
    `returns_playoffs_age` int(11) DEFAULT NULL,
    `returns_playoffs_all_purpose_yds` int(11) DEFAULT NULL,
    `returns_playoffs_g` int(11) DEFAULT NULL,
    `returns_playoffs_gs` int(11) DEFAULT NULL,
    `returns_playoffs_kick_ret` int(11) DEFAULT NULL,
    `returns_playoffs_kick_ret_long` int(11) DEFAULT NULL,
    `returns_playoffs_kick_ret_td` int(11) DEFAULT NULL,
    `returns_playoffs_kick_ret_yds` int(11) DEFAULT NULL,
    `returns_playoffs_kick_ret_yds_per_ret` float DEFAULT NULL,
    `returns_playoffs_pos` varchar(7) DEFAULT NULL,
    `returns_playoffs_punt_ret` int(11) DEFAULT NULL,
    `returns_playoffs_punt_ret_long` int(11) DEFAULT NULL,
    `returns_playoffs_punt_ret_td` int(11) DEFAULT NULL,
    `returns_playoffs_punt_ret_yds` int(11) DEFAULT NULL,
    `returns_playoffs_punt_ret_yds_per_ret` float DEFAULT NULL,
    `returns_playoffs_team` varchar(3) DEFAULT NULL,
    `returns_playoffs_year_id` int(11) DEFAULT NULL,
    `returns_pos` varchar(17) DEFAULT NULL,
    `returns_punt_ret` int(11) DEFAULT NULL,
    `returns_punt_ret_long` int(11) DEFAULT NULL,
    `returns_punt_ret_td` int(11) DEFAULT NULL,
    `returns_punt_ret_yds` int(11) DEFAULT NULL,
    `returns_punt_ret_yds_per_ret` float DEFAULT NULL,
    `returns_team` varchar(3) DEFAULT NULL,
    `returns_uniform_number` int(11) DEFAULT NULL,
    `returns_year_id` varchar(5) DEFAULT NULL,
    `scoring_age` int(11) DEFAULT NULL,
    `scoring_alltd` int(11) DEFAULT NULL,
    `scoring_av` int(11) DEFAULT NULL,
    `scoring_ditd` int(11) DEFAULT NULL,
    `scoring_fgm` int(11) DEFAULT NULL,
    `scoring_frtd` int(11) DEFAULT NULL,
    `scoring_g` int(11) DEFAULT NULL,
    `scoring_gs` int(11) DEFAULT NULL,
    `scoring_krtd` int(11) DEFAULT NULL,
    `scoring_otd` int(11) DEFAULT NULL,
    `scoring_playoffs_age` int(11) DEFAULT NULL,
    `scoring_playoffs_alltd` int(11) DEFAULT NULL,
    `scoring_playoffs_ditd` int(11) DEFAULT NULL,
    `scoring_playoffs_fgm` int(11) DEFAULT NULL,
    `scoring_playoffs_frtd` int(11) DEFAULT NULL,
    `scoring_playoffs_g` int(11) DEFAULT NULL,
    `scoring_playoffs_gs` int(11) DEFAULT NULL,
    `scoring_playoffs_krtd` int(11) DEFAULT NULL,
    `scoring_playoffs_otd` int(11) DEFAULT NULL,
    `scoring_playoffs_points_per_g` int(11) DEFAULT NULL,
    `scoring_playoffs_pos` varchar(7) DEFAULT NULL,
    `scoring_playoffs_prtd` int(11) DEFAULT NULL,
    `scoring_playoffs_rectd` int(11) DEFAULT NULL,
    `scoring_playoffs_rushtd` int(11) DEFAULT NULL,
    `scoring_playoffs_safety_md` int(11) DEFAULT NULL,
    `scoring_playoffs_scoring` int(11) DEFAULT NULL,
    `scoring_playoffs_team` varchar(3) DEFAULT NULL,
    `scoring_playoffs_two_pt_md` int(11) DEFAULT NULL,
    `scoring_playoffs_xpm` int(11) DEFAULT NULL,
    `scoring_playoffs_year_id` int(11) DEFAULT NULL,
    `scoring_points_per_g` int(11) DEFAULT NULL,
    `scoring_pos` varchar(14) DEFAULT NULL,
    `scoring_prtd` int(11) DEFAULT NULL,
    `scoring_rectd` int(11) DEFAULT NULL,
    `scoring_rushtd` int(11) DEFAULT NULL,
    `scoring_safety_md` int(11) DEFAULT NULL,
    `scoring_scoring` int(11) DEFAULT NULL,
    `scoring_team` varchar(3) DEFAULT NULL,
    `scoring_two_pt_md` int(11) DEFAULT NULL,
    `scoring_uniform_number` int(11) DEFAULT NULL,
    `scoring_xpm` int(11) DEFAULT NULL,
    `scoring_year_id` varchar(6) DEFAULT NULL,
    `year` varchar(6) DEFAULT NULL,
    `av` int(11) DEFAULT NULL,
    `pfr_player_id` varchar(10) NOT NULL,
    PRIMARY KEY (`player_seasons_id`),
    KEY `pfr_player_id_idx` (`pfr_player_id`)
) ENGINE=InnoDB AUTO_INCREMENT=90466 DEFAULT CHARSET=utf8 


 select `scoring_playoffs_team`,
`returns_team`,
`returns_playoffs_team`,
`receiving_and_rushing_team`,
`receiving_and_rushing_playoffs_team`
`passing_team`,
`passing_playoffs_team`,
`passing_advanced_team`,
`kicking_team`,
`defense_team`,
`defense_playoffs_team`
from player_seasons
where IFNULL(`scoring_team` IS NOT NULL, 0) +
IFNULL(`scoring_playoffs_team` IS NOT NULL, 0) +
IFNULL(`returns_team` IS NOT NULL, 0) +
IFNULL(`returns_playoffs_team` IS NOT NULL, 0) +
IFNULL(`receiving_and_rushing_team` IS NOT NULL, 0) +
IFNULL(`receiving_and_rushing_playoffs_team` IS NOT NULL, 0) +
IFNULL(`passing_team` IS NOT NULL, 0) +
IFNULL(`passing_playoffs_team` IS NOT NULL, 0) +
IFNULL(`passing_advanced_team` IS NOT NULL, 0) +
IFNULL(`kicking_team` IS NOT NULL, 0) +
IFNULL(`defense_team` IS NOT NULL, 0) +
IFNULL(`defense_playoffs_team` IS NOT NULL, 0) > 7
